# Generated by Django 5.0.6 on 2024-05-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
